### ISSUE TITLE
Changing Send server does not work

### ISSUE THREAD

**Issue by NicolaiVdS** [tdulcet/Thunderbird-Send#1]
I just installed the plugin to test it my self and used my own Send server.

setting the URL to https://send.nvds.be and clicking verify gives the success toast, but when using it i get following 
![afbeelding](https://user-images.githubusercontent.com/5257222/117661143-483f7700-b19e-11eb-8403-1c05317c025c.png)

so as you can see its uploading it to the default server

**Comment by tdulcet** [comment]
Thanks for testing it and for the bug report!

The [AutomaticSettings](https://github.com/TinyWebEx/AutomaticSettings) library caches the settings by default and it looks like that is causing issues here. I will fix this in my next version. In the meantime, you should be able to either click the “Reload” button on the same page you installed it from or restart Thunderbird to resolve the issue.

**Comment by NicolaiVdS** [comment]
@tdulcet can confirm that using the reload button works ;)

**Comment by tdulcet** [comment]
@NicolaiVdS I fixed it in https://github.com/tdulcet/Thunderbird-Send/commit/047197ec443c213e4f65a8b22c48e13b9fff92ad. It should now get the current settings before uploading each file. You should be able to update by just running `git pull`.

**Comment by NicolaiVdS** [comment]
just did a pull and it works correctly now :D Cant wait for the first release
