### ISSUE TITLE
language setting for the sent

### ISSUE THREAD

**Issue by ok1vaw** [tdulcet/Thunderbird-Send#10]
In case of having Thunderbird in certain language (Czech) when I compose an email in English, the Thunderbird Send attachment info and link is written in the Czech language too, not in English. It would be nice to have a possibility to change the language of the info of the Thunderbird in English.
![obrazek](https://github.com/tdulcet/Thunderbird-Send/assets/6250023/947a694b-433a-4ecc-ae4c-b8e5054803de)

**Comment by tdulcet** [comment]
Yes, I agree. Unfortunately, the information shown in your screenshot is automatically added to the e-mails by Thunderbird and add-ons have very little control over it. Usually this is a good thing, as it reduces the complexity of FileLink add-ons and provides consistency, but it also means that the add-on cannot change the language.

Anyway, if this is a feature you want, I would encourage you to file a bug about it on Bugzilla: https://bugzilla.mozilla.org.

**Comment by tdulcet** [comment]
If you do file a bug about this on BMO, please share the link here so I can follow along. Feel free to also reopen this issue if you have any questions.
