### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by hector29200** [tdulcet/Thunderbird-Send#11]
Hi,
Thanks a lot for your job.
I just installed your plugin and unfortunately it doesn't work for me.
Each time I try to link a file, the process begins well but a few seconds after the upload begins a message appears :
"The download or time limit is likely above the maximum supported by this Send service instance"
The current file is about 3,5 Mo and the plugin set to 2 Go...
Do I miss something into the settings ?
Best regards

**Comment by tdulcet** [comment]
Thanks for installing the add-on. I am sorry to hear that it is not working for you.

What values did you enter for the download and time limit for the file? The default Send service instance currently supports a maximum of 10 downloads and 3 days respectively. If you try to enter values above those maximums, you would see that error message you quoted.

Note that there are other public Send instances you could configure the add-on to use, some of which have higher limits. See here for a list: https://github.com/timvisee/send-instances

**Comment by hector29200** [comment]
Issue solved !
I had set 5 days as a time limit...so it did not work.
Now it's working like a charm, thanks to you
