### ISSUE TITLE
Italian translation: a "typo" at line 564

### ISSUE THREAD

**Issue by topoldo** [tdulcet/Thunderbird-Send#21]
Dear Sirs,
I checked the Italian translation of this extension for Thuderbird & Betterbird.
I just want to point out a little "typo" at line 564 of the Italian translation:
The original text is this:

`564  "message": "Error: Impossibile eliminare il file caricato “$filename$”: $text$. Forse è già scaduto od eliminato.",`

The corerct one should be:

`564  "message": "Errore: Impossibile eliminare il file caricato “$filename$”: $text$. Forse è già scaduto od eliminato.",`

As I said, it is just a little typo but I think it is worth of correction in a very well done translation.

Yours sincerely,
Leopoldo aka Topoldo

**Comment by tdulcet** [comment]
Thanks for the report. @mike-cuche translated this add-on to Italian, so I will let him decide if this should be changed.

**Comment by mike-cuche** [comment]
Il 29/08/24 12:31, Teal Dulcet ha scritto:
> Thanks for the report. @mike-cuche <https://github.com/mike-cuche> 
> translated this add-on to Italian, so I will let him decide if this 
> should be changed.
> 

Hello, yes, I approve the correction! :)

**Comment by tdulcet** [comment]
Thanks! I will fix this in my next commit, but pull requests are welcome if someone wants to fix it sooner.
