### ISSUE TITLE
Links expire too soon on default instance

### ISSUE THREAD

**Issue by ElhemEnohpi** [tdulcet/Thunderbird-Send#3]
Hi, thanks for maintaining this, and sorry if this isn't the right place to report this... I installed it for the first time yesterday, and sent some files to a couple of people. I set the "default time limit" to 10080, didn't change anything else. The upload and link seemed to work, but the links have already expired, less than 24 hours later.

One more thing, the message seems to be delivered with a strange attachment, "part 1.2", which is empty if you try to save it. Is that normal, and can it be deleted somehow before sending, so that recipients don't think that's the actual file attachment?

**Comment by timvisee** [comment]
> I installed it for the first time yesterday, and sent some files to a couple of people. I set the "default time limit" to 10080, didn't change anything else. The upload and link seemed to work, but the links have already expired, less than 24 hours later.

The files may have expired because of a low download limit. I believe it defaults to 1 download.

Files expire when the download limit OR expiry time is reached.

Setting a higher limit could help.

**Comment by tdulcet** [comment]
@timvisee Thanks for answering that!

> One more thing, the message seems to be delivered with a strange attachment, "part 1.2", which is empty if you try to save it. Is that normal, and can it be deleted somehow before sending, so that recipients don't think that's the actual file attachment?

Yes, Thunderbird does this automatically, so that uses can still search for messages with an attachment. However, there is currently a discussion about changing or removing it, see [bug 1670791](https://bugzilla.mozilla.org/show_bug.cgi?id=1670791) for more information.

**Comment by ElhemEnohpi** [comment]
Thanks! I guess I didn't quite understand what the "download limit" setting means (though it's obvious now), and thought it had something to do with a server setting for how many files you can download at the same time or something. After I sent it, I tested the link to make sure it worked, making it expire. Maybe it could be a little more explicit, like "maximum number of times the file can be downloaded before expiring". Or maybe it's just me...

Thanks also for the link to the Thunderbird bug, I made a comment there. It seems to me that having a psuedo-attachment is more confusing than it's worth. The file is not actually attached, it's converted to a link, like I'm used to with WeTransfer or DropBox. So I wouldn't expect there to also be an attachment, especially a strange empty one. Even if the attachment led to the download link, it would be confusing because the link is already in the message.

**Comment by tdulcet** [comment]
> Maybe it could be a little more explicit, like "maximum number of times the file can be downloaded before expiring". Or maybe it's just me...

Thanks for the feedback. I just updated my local copy of the extension to say “The file will expire after this number of downloads” on both the account management page and popup. This will be included with my next version of the add-on.

I am closing this issue, as I believe we have answered all of your questions.
