### ISSUE TITLE
https://send.vis.ee blocked by Malwarebytes 

### ISSUE THREAD

**Issue by pgbexplorer** [tdulcet/Thunderbird-Send#4]
I have just set up Send Provider for Thunderbird and it worked beautifully until the download was blocked by Malwarebytes, screenshot attached. It didn't appear until I attempted to download the file. I chose the test file itself to be large but innocuous, the Thunderbird installation file. I then checked https://send.vis.ee on the Norton website and it was again identified as dangerous. All other URL checkers that I tried didn't identify https://send.vis.ee as dangerous. Presuming that this https://send.vis.ee is not dangerous and that Malwarebytes and Norton are just being overly cautious, I suggest that you contact them and seek to have https://send.vis.ee removed from their lists of dangerous URLs.
![Screenshot 2022-01-14 143137](https://user-images.githubusercontent.com/97719592/149454215-177a0c4a-f128-4f72-9bb6-08cfe95f4aa0.jpg)
![Screenshot 2022-01-14 140345](https://user-images.githubusercontent.com/97719592/149454231-7f972e1c-3d40-44c4-8723-78e19b8c0940.jpg)

**Comment by timvisee** [comment]
That is unfortunate! I'm the one hosting https://send.vis.ee/

I'll try to contact them to see what I can do about it.

Thanks for the detailed report.

**Comment by tdulcet** [comment]
Thanks for the information. As @timvisee said above, he is the one who hosts the https://send.vis.ee Send instance, so in the future you should report any issues with it directly to his repository: https://github.com/timvisee/send.

My FileLink provider add-on works with all Send service instances, so in the meantime you could set it to use one of the other instances, which will hopefully not be blocked by your antivirus software. See [here](https://github.com/timvisee/send-instances/#instances) for a list of public Send service instances.
