### ISSUE TITLE
Never complete linking the attachement

### ISSUE THREAD

**Issue by ydroneaud** [tdulcet/Thunderbird-Send#5]
Here the error message:

> JavaScript error: moz-extension://8e389ed7-33bd-47dc-8a79-0cc216985088/background.js, line 624: Error: 400

**Comment by tdulcet** [comment]
Thanks for the bug report! Some questions:

* Which version of Thunderbird and the add-on are you using?
* Which Send service instance did you use? The default [send.vis.ee](https://send.vis.ee/)?
* Are you able to reproduce the issue? If so, what values for the download limit and time limit are you using?

I suspect the issue is that you used too high of a download limit and/or time limit for the Send instance. I believe the default Send instance only supports maximum values of 20 downloads and 7 days respectively.

**Comment by ydroneaud** [comment]
> Thanks for the bug report! Some questions:
> 
>     * Which version of Thunderbird and the add-on are you using?
> 

Thunderbird 91.5.0 (91.5.0+build1-0ubuntu0.21.10.1)

FileLink provider for Send 1.1

>     * Which Send service instance did you use? The default [send.vis.ee](https://send.vis.ee/)?
> 

The default

>     * Are you able to reproduce the issue? If so, what values for the download limit and time limit are you using?
> 

I used 100 as download limit and 50081 as time limit.

> 
> I suspect the issue is that you used too high of a download limit and/or time limit for the Send instance. I believe the default Send instance only supports maximum values of 20 downloads and 7 days respectively.

I confirm, using those limits, adding the link worked.

**Comment by tdulcet** [comment]
> I used 100 as download limit and 50081 as time limit.

50081 minutes is around 34.7 days.

> I confirm, using those limits, adding the link worked.

OK, if you want to use those limits, you would currently need to select a different Send service instance from the default. I do not believe any of them support time limits of 34 days, but some do support up to 30 days and 100 downloads. You can see [here](https://github.com/timvisee/send-instances/#instances) for a list of public Send service instances.

I will update the next version of the add-on to show a more helpful error message in this case.

**Comment by ydroneaud** [comment]
> > I used 100 as download limit and 50081 as time limit.

> I will update the next version of the add-on to show a more helpful error message in this case.

Thanks

**Comment by timvisee** [comment]
You might find the following list interesting, as some hosts have different limits:

https://github.com/timvisee/send-instances/
