### ISSUE TITLE
Upload files fails in version 2.0 on Thunderbird 102.12.0

### ISSUE THREAD

**Issue by antviro** [tdulcet/Thunderbird-Send#9]
Hi,

All files were not being uploaded to any server under version 2.0. App produced a short error message like "unable to upload the file", and not going on. I have not investigated into the issue, but I fixed it by downgrading till 1.2 version, where it works perfectly.

I am using Thunderbird 102.12.0 under GNU Linux Debian 5. I guess it is probably related with thunderbird version, once I upgrade it (after summer), I will tell you if it gets solved (and it is just that version 2.0 requires a higher version).

Best regards and thank you for this wonderful tool,
Antonio

**Comment by tdulcet** [comment]
Hello Antonio,

Thanks for the bug report and for using my add-on! I am sorry to hear that version 2.0 of the add-on is not working for you.

When does the error occur for you in the upload process? Are you uploading multiple files at once? The version 2.0 update supports both Thunderbird 102 and 115, so you should not have any problems. I just uploaded a file with version 2.0 in Thunderbird 102.12 and it worked as expected.

The time limit in version 2.0 is now specified in separate minutes, hours and days fields, so is it possible that you entered your desired value in the wrong field, which resulted in a time limit above the maximum supported by the Send instance? This would cause an error.

If that is not the issue, after attempting to upload a file, can you please go to the Thunderbird menu “≡”, click “🧩 Add-ons and Themes”, “Extensions” on the left, the gear menu “⚙” on top and select “Debug Add-ons”. Then, scroll down that page and next to “FileLink provider for Send” click the “Inspect” button. Lastly, click the “Console” tab (if it is not already selected) on this new page and let me know if there are any errors (in red). Please see [these screenshots](https://developer.thunderbird.net/add-ons/hello-world-add-on#installing) for more information.

**Comment by antviro** [comment]
Hi, 

Thanks to your guiding, I have found all errors where caused by the time, and then, I realise that all the URLs where pointing to send.vis.ee instead of for instance transfer.acted.org (may it have changed while upgrading?), and so the time limit was not complying with send.vis.ee

After realising of that, I fixed the server names that I used and it is working perfectly.

Thank you very much!
Antonio
